# Generated by Django 5.0.1 on 2024-02-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='borrn_date',
            new_name='born_date',
        ),
    ]
