# Generated by Django 5.0.1 on 2024-02-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_borrn_date_author_born_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='fullname',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='borrn_date',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='fullname',
            new_name='name',
        ),
    ]
