# Generated by Django 5.0.1 on 2024-02-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rename_fullname_quote_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
